import 'package:islam_app/models/rest_api/quran_pages_settings.dart';

class QuranConstant {
  static List<QuranPagesSettings> quranList = [
    QuranPagesSettings(
      pageNumber: 1,
      sorahNameReference: "Al-Fatiha",
      juzaNumber: 1,
      hezebNumber: 1,
      hezebStatus: Hezeb.part,
    ),
    QuranPagesSettings(
      pageNumber: 2,
      sorahNameReference: "Al-Baqarah",
      juzaNumber: 1,
      hezebNumber: 1,
      hezebStatus: Hezeb.idl,
    ),
    QuranPagesSettings(
      pageNumber: 3,
      sorahNameReference: "Al-Baqarah",
      juzaNumber: 1,
      hezebNumber: 1,
      hezebStatus: Hezeb.idl,
    ),
    QuranPagesSettings(
      pageNumber: 4,
      sorahNameReference: "Al-Baqarah",
      juzaNumber: 1,
      hezebNumber: 1,
      hezebStatus: Hezeb.idl,
    ),
    QuranPagesSettings(
      pageNumber: 5,
      sorahNameReference: "Al-Baqarah",
      juzaNumber: 1,
      hezebNumber: 1,
      hezebStatus: Hezeb.quarter,
    ),
    QuranPagesSettings(
      pageNumber: 6,
      sorahNameReference: "Al-Baqarah",
      juzaNumber: 1,
      hezebNumber: 1,
      hezebStatus: Hezeb.idl,
    ),
    QuranPagesSettings(
      pageNumber: 7,
      sorahNameReference: "Al-Baqarah",
      juzaNumber: 1,
      hezebNumber: 1,
      hezebStatus: Hezeb.half,
    ),
    QuranPagesSettings(
      pageNumber: 8,
      sorahNameReference: "Al-Baqarah",
      juzaNumber: 1,
      hezebNumber: 1,
      hezebStatus: Hezeb.idl,
    ),
    QuranPagesSettings(
      pageNumber: 9,
      sorahNameReference: "Al-Baqarah",
      juzaNumber: 1,
      hezebNumber: 1,
      hezebStatus: Hezeb.threeQuarters,
    ),
    QuranPagesSettings(
      pageNumber: 10,
      sorahNameReference: "Al-Baqarah",
      juzaNumber: 1,
      hezebNumber: 1,
      hezebStatus: Hezeb.idl,
    ),
    QuranPagesSettings(
      pageNumber: 11,
      sorahNameReference: "Al-Baqarah",
      juzaNumber: 1,
      hezebNumber: 2,
      hezebStatus: Hezeb.part,
    ),
    QuranPagesSettings(
      pageNumber: 12,
      sorahNameReference: "Al-Baqarah",
      juzaNumber: 1,
      hezebNumber: 2,
      hezebStatus: Hezeb.idl,
    ),
    QuranPagesSettings(
      pageNumber: 13,
      sorahNameReference: "Al-Baqarah",
      juzaNumber: 1,
      hezebNumber: 2,
      hezebStatus: Hezeb.idl,
    ),
    QuranPagesSettings(
      pageNumber: 14,
      sorahNameReference: "Al-Baqarah",
      juzaNumber: 1,
      hezebNumber: 2,
      hezebStatus: Hezeb.quarter,
    ),
    QuranPagesSettings(
      pageNumber: 15,
      sorahNameReference: "Al-Baqarah",
      juzaNumber: 1,
      hezebNumber: 2,
      hezebStatus: Hezeb.idl,
    ),
    QuranPagesSettings(
      pageNumber: 16,
      sorahNameReference: "Al-Baqarah",
      juzaNumber: 1,
      hezebNumber: 2,
      hezebStatus: Hezeb.idl,
    ),
    QuranPagesSettings(
      pageNumber: 17,
      sorahNameReference: "Al-Baqarah",
      juzaNumber: 1,
      hezebNumber: 2,
      hezebStatus: Hezeb.half,
    ),
    QuranPagesSettings(
      pageNumber: 18,
      sorahNameReference: "Al-Baqarah",
      juzaNumber: 1,
      hezebNumber: 2,
      hezebStatus: Hezeb.idl,
    ),
    QuranPagesSettings(
      pageNumber: 19,
      sorahNameReference: "Al-Baqarah",
      juzaNumber: 1,
      hezebNumber: 2,
      hezebStatus: Hezeb.threeQuarters,
    ),
    QuranPagesSettings(
      pageNumber: 20,
      sorahNameReference: "Al-Baqarah",
      juzaNumber: 1,
      hezebNumber: 2,
      hezebStatus: Hezeb.idl,
    ),
    QuranPagesSettings(
      pageNumber: 21,
      sorahNameReference: "Al-Baqarah",
      juzaNumber: 1,
      hezebNumber: 2,
      hezebStatus: Hezeb.idl,
    ),
    QuranPagesSettings(
      pageNumber: 22,
      sorahNameReference: "Al-Baqarah",
      juzaNumber: 2,
      hezebNumber: 3,
      hezebStatus: Hezeb.part,
    ),
    QuranPagesSettings(
      pageNumber: 23,
      sorahNameReference: "Al-Baqarah",
      juzaNumber: 2,
      hezebNumber: 3,
      hezebStatus: Hezeb.idl,
    ),
    QuranPagesSettings(
      pageNumber: 24,
      sorahNameReference: "Al-Baqarah",
      juzaNumber: 2,
      hezebNumber: 3,
      hezebStatus: Hezeb.quarter,
    ),
    QuranPagesSettings(
      pageNumber: 25,
      sorahNameReference: "Al-Baqarah",
      juzaNumber: 2,
      hezebNumber: 3,
      hezebStatus: Hezeb.idl,
    ),
    QuranPagesSettings(
      pageNumber: 26,
      sorahNameReference: "Al-Baqarah",
      juzaNumber: 2,
      hezebNumber: 3,
      hezebStatus: Hezeb.idl,
    ),
    QuranPagesSettings(
      pageNumber: 27,
      sorahNameReference: "Al-Baqarah",
      juzaNumber: 2,
      hezebNumber: 3,
      hezebStatus: Hezeb.half,
    ),
    QuranPagesSettings(
      pageNumber: 28,
      sorahNameReference: "Al-Baqarah",
      juzaNumber: 2,
      hezebNumber: 3,
      hezebStatus: Hezeb.idl,
    ),
    QuranPagesSettings(
      pageNumber: 29,
      sorahNameReference: "Al-Baqarah",
      juzaNumber: 2,
      hezebNumber: 3,
      hezebStatus: Hezeb.threeQuarters,
    ),
    QuranPagesSettings(
      pageNumber: 30,
      sorahNameReference: "Al-Baqarah",
      juzaNumber: 2,
      hezebNumber: 3,
      hezebStatus: Hezeb.idl,
    ),
    QuranPagesSettings(
      pageNumber: 31,
      sorahNameReference: "Al-Baqarah",
      juzaNumber: 2,
      hezebNumber: 3,
      hezebStatus: Hezeb.idl,
    ),
    QuranPagesSettings(
      pageNumber: 32,
      sorahNameReference: "Al-Baqarah",
      juzaNumber: 2,
      hezebNumber: 4,
      hezebStatus: Hezeb.part,
    ),
    QuranPagesSettings(
      pageNumber: 33,
      sorahNameReference: "Al-Baqarah",
      juzaNumber: 2,
      hezebNumber: 4,
      hezebStatus: Hezeb.idl,
    ),
    QuranPagesSettings(
      pageNumber: 34,
      sorahNameReference: "Al-Baqarah",
      juzaNumber: 2,
      hezebNumber: 4,
      hezebStatus: Hezeb.quarter,
    ),
    QuranPagesSettings(
      pageNumber: 35,
      sorahNameReference: "Al-Baqarah",
      juzaNumber: 2,
      hezebNumber: 4,
      hezebStatus: Hezeb.idl,
    ),
    QuranPagesSettings(
      pageNumber: 36,
      sorahNameReference: "Al-Baqarah",
      juzaNumber: 2,
      hezebNumber: 4,
      hezebStatus: Hezeb.idl,
    ),
    QuranPagesSettings(
      pageNumber: 37,
      sorahNameReference: "Al-Baqarah",
      juzaNumber: 2,
      hezebNumber: 4,
      hezebStatus: Hezeb.half,
    ),
    QuranPagesSettings(
      pageNumber: 38,
      sorahNameReference: "Al-Baqarah",
      juzaNumber: 2,
      hezebNumber: 4,
      hezebStatus: Hezeb.half,
    ),
  ];
}
