
name: utilities

packages:
  - utilities/**
  - .

scripts:
  analyze:
    exec: dart analyze .
  pub-get:
    run: melos exec -- "flutter pub get"

command:
  bootstrap:
    usePubspecOverrides: true
  clean:
    hooks:
      post: melos exec --flutter -c 1 -- flutter clean
  format:
    hooks:
      post: melos exec --flutter -c 1 -- dart format lib