
name: sub_projects

packages:
  - sub_projects/islam_mob_adhan/*
  - sub_projects/custom_widgets/*
  - sub_projects/azkar/*
  - .

scripts:
  analyze:
    exec: dart analyze .
  pub-get:
    run: melos exec -- "flutter pub get"

command:
  bootstrap:
    usePubspecOverrides: true