import 'package:flutter_gen/gen_l10n/app_localizations.dart';

extension AppLocalizationsExtension on AppLocalizations {
  String getLocalizedString(String key) {
    switch (key) {
      case 'quranSorahName1':
        return quranSorahName1;
      case 'quranSorahName2':
        return quranSorahName2;
      case 'quranSorahName3':
        return quranSorahName3;
      case 'quranSorahName4':
        return quranSorahName4;
      case 'quranSorahName5':
        return quranSorahName5;
      case 'quranSorahName6':
        return quranSorahName6;
      case 'quranSorahName7':
        return quranSorahName7;
      case 'quranSorahName8':
        return quranSorahName8;
      case 'quranSorahName9':
        return quranSorahName9;
      case 'quranSorahName10':
        return quranSorahName10;
      case 'quranSorahName11':
        return quranSorahName11;
      case 'quranSorahName12':
        return quranSorahName12;
      case 'quranSorahName13':
        return quranSorahName13;
      case 'quranSorahName14':
        return quranSorahName14;
      case 'quranSorahName15':
        return quranSorahName15;
      case 'quranSorahName16':
        return quranSorahName16;
      case 'quranSorahName17':
        return quranSorahName17;
      case 'quranSorahName18':
        return quranSorahName18;
      case 'quranSorahName19':
        return quranSorahName19;
      case 'quranSorahName20':
        return quranSorahName20;
      case 'quranSorahName21':
        return quranSorahName21;
      case 'quranSorahName22':
        return quranSorahName22;
      case 'quranSorahName23':
        return quranSorahName23;
      case 'quranSorahName24':
        return quranSorahName24;
      case 'quranSorahName25':
        return quranSorahName25;
      case 'quranSorahName26':
        return quranSorahName26;
      case 'quranSorahName27':
        return quranSorahName27;
      case 'quranSorahName28':
        return quranSorahName28;
      case 'quranSorahName29':
        return quranSorahName29;
      case 'quranSorahName30':
        return quranSorahName30;
      case 'quranSorahName31':
        return quranSorahName31;
      case 'quranSorahName32':
        return quranSorahName32;
      case 'quranSorahName33':
        return quranSorahName33;
      case 'quranSorahName34':
        return quranSorahName34;
      case 'quranSorahName35':
        return quranSorahName35;
      case 'quranSorahName36':
        return quranSorahName36;
      case 'quranSorahName37':
        return quranSorahName37;
      case 'quranSorahName38':
        return quranSorahName38;
      case 'quranSorahName39':
        return quranSorahName39;
      case 'quranSorahName40':
        return quranSorahName40;
      case 'quranSorahName41':
        return quranSorahName41;
      case 'quranSorahName42':
        return quranSorahName42;
      case 'quranSorahName43':
        return quranSorahName43;
      case 'quranSorahName44':
        return quranSorahName44;
      case 'quranSorahName45':
        return quranSorahName45;
      case 'quranSorahName46':
        return quranSorahName46;
      case 'quranSorahName47':
        return quranSorahName47;
      case 'quranSorahName48':
        return quranSorahName48;
      case 'quranSorahName49':
        return quranSorahName49;
      case 'quranSorahName50':
        return quranSorahName50;
      case 'quranSorahName51':
        return quranSorahName51;
      case 'quranSorahName52':
        return quranSorahName52;
      case 'quranSorahName53':
        return quranSorahName53;
      case 'quranSorahName54':
        return quranSorahName54;
      case 'quranSorahName55':
        return quranSorahName55;
      case 'quranSorahName56':
        return quranSorahName56;
      case 'quranSorahName57':
        return quranSorahName57;
      case 'quranSorahName58':
        return quranSorahName58;
      case 'quranSorahName59':
        return quranSorahName59;
      case 'quranSorahName60':
        return quranSorahName60;
      case 'quranSorahName61':
        return quranSorahName61;
      case 'quranSorahName62':
        return quranSorahName62;
      case 'quranSorahName63':
        return quranSorahName63;
      case 'quranSorahName64':
        return quranSorahName64;
      case 'quranSorahName65':
        return quranSorahName65;
      case 'quranSorahName66':
        return quranSorahName66;
      case 'quranSorahName67':
        return quranSorahName67;
      case 'quranSorahName68':
        return quranSorahName68;
      case 'quranSorahName69':
        return quranSorahName69;
      case 'quranSorahName70':
        return quranSorahName70;
      case 'quranSorahName71':
        return quranSorahName71;
      case 'quranSorahName72':
        return quranSorahName72;
      case 'quranSorahName73':
        return quranSorahName73;
      case 'quranSorahName74':
        return quranSorahName74;
      case 'quranSorahName75':
        return quranSorahName75;
      case 'quranSorahName76':
        return quranSorahName76;
      case 'quranSorahName77':
        return quranSorahName77;
      case 'quranSorahName78':
        return quranSorahName78;
      case 'quranSorahName79':
        return quranSorahName79;
      case 'quranSorahName80':
        return quranSorahName80;
      case 'quranSorahName81':
        return quranSorahName81;
      case 'quranSorahName82':
        return quranSorahName82;
      case 'quranSorahName83':
        return quranSorahName83;
      case 'quranSorahName84':
        return quranSorahName84;
      case 'quranSorahName85':
        return quranSorahName85;
      case 'quranSorahName86':
        return quranSorahName86;
      case 'quranSorahName87':
        return quranSorahName87;
      case 'quranSorahName88':
        return quranSorahName88;
      case 'quranSorahName89':
        return quranSorahName89;
      case 'quranSorahName90':
        return quranSorahName90;
      case 'quranSorahName91':
        return quranSorahName91;
      case 'quranSorahName92':
        return quranSorahName92;
      case 'quranSorahName93':
        return quranSorahName93;
      case 'quranSorahName94':
        return quranSorahName94;
      case 'quranSorahName95':
        return quranSorahName95;
      case 'quranSorahName96':
        return quranSorahName96;
      case 'quranSorahName97':
        return quranSorahName97;
      case 'quranSorahName98':
        return quranSorahName98;
      case 'quranSorahName99':
        return quranSorahName99;
      case 'quranSorahName100':
        return quranSorahName100;
      case 'quranSorahName101':
        return quranSorahName101;
      case 'quranSorahName102':
        return quranSorahName102;
      case 'quranSorahName103':
        return quranSorahName103;
      case 'quranSorahName104':
        return quranSorahName104;
      case 'quranSorahName105':
        return quranSorahName105;
      case 'quranSorahName106':
        return quranSorahName106;
      case 'quranSorahName107':
        return quranSorahName107;
      case 'quranSorahName108':
        return quranSorahName108;
      case 'quranSorahName109':
        return quranSorahName109;
      case 'quranSorahName110':
        return quranSorahName110;
      case 'quranSorahName111':
        return quranSorahName111;
      case 'quranSorahName112':
        return quranSorahName112;
      case 'quranSorahName113':
        return quranSorahName113;
      case 'quranSorahName114':
        return quranSorahName114;
      case "1":
        return jusone;
      case "2":
        return justwo;
      case "3":
        return justhree;
      case "4":
        return jusfour;
      case "5":
        return jusfive;
      case "6":
        return jussix;
      case "7":
        return jusseven;
      case "8":
        return juseight;
      case "9":
        return jusnine;
      case "10":
        return justen;
      case "11":
        return juseleven;
      case "12":
        return justwelve;
      case "13":
        return justhirteen;
      case "14":
        return jusfourteen;
      case "15":
        return jusfifteen;
      case "16":
        return jussixteen;
      case "17":
        return jusseventeen;
      case "18":
        return juseightteen;
      case "19":
        return jusnineteen;
      case "20":
        return justtwenty;
      case "21":
        return justwentyone;
      case "22":
        return justwentytwo;
      case "23":
        return justwentythree;
      case "24":
        return justwentyfour;
      case "25":
        return justwentyfive;
      case "26":
        return justwentysix;
      case "27":
        return justwentyseven;
      case "28":
        return justwentyeight;
      case "29":
        return justwentynine;
      case "30":
        return justhirty;
      default:
        return ''; // Or a default string if the key is not found
    }
  }
}
