targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          include_if_null: false
        generate_for:
          - lib/src/data/models/*.dart
      freezed:
        options:
          format: false
        generate_for:
          - lib/src/data/models/*.dart
      injectable_generator|injectable_builder:
        generate_for:
          - lib/src/di/*.dart
