enum PrayNotificationType {
  allNotificationForToday,
  allNotificationForThreeDay,
  allNotificationForWeekDay,
  fajir,
  duhir,
  asr,
  magrieb,
  isha,
  sunriseTime,
  jom3aAlkahf,
  jom3aDo3aa,
  qeyamAlLayel,
  before15Min,
  pushNotification,
}
