# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

platform :ios do
  before_all do
    load_asc_api_token
  end

  desc "Load the App Store Connect API token"
  lane :load_asc_api_token do
    app_store_connect_api_key(
      key_id: ENV["APPSTORE_ASC_KEY_ID"],
      issuer_id: ENV["APPSTORE_ASC_ISSUER_ID"],
      key_content: ENV["APPSTORE_ASC_KEY_P8"],
      is_key_content_base64: true,
      in_house: false
    )
  end

  desc "Set Info.plist Version and Build Number"
  lane :set_full_version do
    version = flutter_version()

    increment_version_number(version_number: version['version_name'])
    increment_build_number(build_number: version['version_code'])
  end

  # desc "Push a new beta build to TestFlight"
  # lane :deploy do

    # set_full_version()

    # setup_ci if is_ci

    # cocoapods(clean_install: is_ci)

    # if is_ci
    #   create_keychain(
    #     name: ENV['MATCH_KEYCHAIN_NAME'],
    #     password: ENV["MATCH_KEYCHAIN_PASSWORD"],
    #     default_keychain: true,
    #     unlock: true,
    #     timeout: 3600,
    #     lock_when_sleeps: false
    #   )
    # end

  #   match(
  #     type: "appstore",
  #     readonly: is_ci,
  #     keychain_name: ENV['MATCH_KEYCHAIN_NAME'],
  #     keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"],
  #   )

  #   build_app(
  #     workspace: "Runner.xcworkspace",
  #     scheme: "Runner",
  #     archive_path: "../build/ios/Runner.xcarchive",
  #     output_directory: "../build/ios/Runner",
  #   )

  #   upload_to_testflight(
  #     api_key_path: "./app_store_connect.json",
  #     ipa: '../build/ios/Runner/Runner.ipa',
  #     skip_waiting_for_build_processing: true,
  #   )
  # end
end