name: database_manager
version: 1.0.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  # hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  test: ^1.25.7
  hive_generator: ^2.0.1
  build_runner: 2.4.12
  lints: ^4.0.0
  json_serializable: 6.8.0
  mockito: ^5.4.4
  dependency_validator: 4.1.0

flutter:
  generate: true
  uses-material-design: true
