name: CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
        - name: 📚 Git Checkout
          uses: actions/checkout@v3

        - name: 🔥 Set Up Java
          uses: actions/setup-java@v3.12.0
          with:
            distribution: 'oracle'
            java-version: '17'

        - name: 🐦 Setup Flutter
          uses: subosito/flutter-action@v2
          with:
            flutter-version: '3.24.1'
            channel: 'stable'
            cache: true

        - name: 🔎 Install Dependencies
          run: flutter pub get
    
        - name: 🔑 Decode Keystore
          run: |
            echo "${{ secrets.KEY_STORE }}" | base64 --decode > android/app/keystore.jks

        - name: 🔑 Create key.properties
          run: |
            echo "keyPassword=${{ secrets.KEY_PASSWORD }}" > android/key.properties
            echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
            echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
            echo "storeFile=keystore.jks" >> android/key.properties
            echo "${{ secrets.GOOGLE_PLAY_STORE_KEY }}" | base64 --decode > android/play_store_secret.json

        - name: 🏗 Build APK
          run: flutter build apk --release
 
        - name: 🏗 Build appBundle
          run: flutter build appbundle
            
        - name: 📦 Set up local.properties
          run: |
              echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties

        # - name: 🎯 Setup Fastlane
        #   uses: ruby/setup-ruby@v1
        #   with:
        #       ruby-version: 3.2 
    
        # - name: 📦 Update RubyGems
        #   run: gem update --system

        # - name: 📦 Cleaning before we start
        #   run: |
        #       flutter clean
        #       rm -rf pubspec.lock
        #       flutter pub get
    
        # - name: 🛠️ Build and Deploy
        #   run: |
        #     make deploy-android

  ios:
    runs-on: macos-latest

    steps:
        - name: 📚 Git Checkout
          uses: actions/checkout@v3

        - name: 🐦 Setup Flutter
          uses: subosito/flutter-action@v2
          with:
            flutter-version: '3.24.1'
            channel: 'stable'
            cache: true

        - name: 🔎 Install Dependencies
          run: flutter pub get

        - name: 🔑 Set up App Store Connect
          run: |
              echo "${{ secrets.APP_STORE_CONNECT }}" | base64 --decode > ios/app_store_connect.json

        # - name: 🎯 Setup Fastlane
        #   uses: ruby/setup-ruby@v1
        #   with:
        #     ruby-version: 3.2 

        # - name: 📦 Update RubyGems
        #   run: gem update --system

        # - name: 📦 Cleaning before we start
        #   run: |
        #       flutter clean
        #       cd ios && rm -rf Podfile.lock
        #       cd ios && rm -rf Pods
        #       cd ios && pod install
        #       cd ..
        #       rm -rf pubspec.lock
        #       flutter pub get
    
        # - name: 🛠️ Build and Deploy
        #   run: |
        #     make deploy-ios
        #   env:
        #     MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        #     MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.GIT_BASIC_AUTHORIZATION }}
        #     FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        #     MATCH_KEYCHAIN_NAME: ${{ secrets.MATCH_KEYCHAIN_NAME }}
        #     MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}

  